# Generated by Django 4.0.1 on 2022-01-18 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Regiao_Fruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome_Fruta', models.CharField(max_length=150)),
                ('Nome_Regiao', models.CharField(max_length=150)),
            ],
        ),
    ]
